### ISSUE TITLE
Push to docker registry fails with `tag does not exist` registry.digitalocean.com/mailio/mailiofrontend:latest

### ISSUE THREAD

**Issue by igorrendulic** [do-community/example-doctl-action#13]
It seems like this might be outdated? It's been working for me for the past 100 deployments up until 1 month ago.

```console
Run docker push registry.digitalocean.com/myrepo/static-example
Using default tag: latest
The push refers to repository [registry.digitalocean.com/myrepo/static-example]
tag does not exist: registry.digitalocean.com/myrepo/static-example:latest
Error: Process completed with exit code 1.
```

Github workflow fix is to add the tag when pushing to registry:

```yaml
 ...
  - name: Push image to DigitalOcean Container Registry
    run: docker push registry.digitalocean.com/myrepo/static-example:$(echo $GITHUB_SHA | head -c7)
...
```
